### ISSUE TITLE
log_file_globs setting inside of targets does not work

### ISSUE THREAD

**Issue by robolson** [square/kochiku#144]
The implementation of individual `log_file_globs` for each target inside of a kochiku.yml does not currently work. The last log file glob specified will always win and overwrite all of the others.

Example:

```
test_command: 'script/ci'
targets:
  - type: unit
    glob: spec/unit/**/*_spec.rb
    log_file_globs:
      - log/test.log
  - type: integration
    glob: spec/integration/**/*_spec.rb
    log_file_globs:
      - log/integration.log
```

Here the unit target will receive a log_file_globs value of "log/integration.log" because that is the last one specified.

This will be difficult to fix so I propose removing the log_file_globs key from the targets section. Users can specify all of their log files in the global key instead.
